"""Add category sequence api_key to tool_configs

Revision ID: 15e04b61681d
Revises: 2a3b4c5d6e7f
Create Date: 2026-04-08 01:40:36.049384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '15e04b61681d'
down_revision: Union[str, None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.add_column('few_shot_examples', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('tool_configs', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('tool_configs', sa.Column('sequence_number', sa.Integer(), server_default='1', nullable=False))
    op.add_column('tool_configs', sa.Column('api_key', sa.String(length=500), nullable=True))
    op.drop_column('tool_configs', 'api_key_encrypted')
    op.drop_column('tool_configs', 'auth_type')
    op.drop_column('tool_configs', 'extra_config')
    op.drop_column('tool_configs', 'base_url')
    op.drop_column('tool_configs', 'extra_headers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_configs', sa.Column('extra_headers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tool_configs', sa.Column('base_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('tool_configs', sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tool_configs', sa.Column('auth_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('tool_configs', sa.Column('api_key_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tool_configs', 'api_key')
    op.drop_column('tool_configs', 'sequence_number')
    op.drop_column('tool_configs', 'category')
    op.drop_column('few_shot_examples', 'embedding')
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
